# Generated by Django 5.2.5 on 2025-09-23 22:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_number', models.CharField(max_length=25, unique=True)),
                ('process_id', models.CharField(blank=True, max_length=100, null=True)),
                ('court_code', models.CharField(blank=True, max_length=10, null=True)),
                ('court_name', models.CharField(blank=True, max_length=200, null=True)),
                ('case_class', models.CharField(blank=True, max_length=200, null=True, verbose_name='Classe')),
                ('subject', models.TextField(blank=True, null=True, verbose_name='Assunto')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor da Causa')),
                ('distribution_date', models.DateField(blank=True, null=True, verbose_name='Data de Distribuição')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='Última Atualização')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Dados Brutos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dados de Processo',
                'verbose_name_plural': 'Dados de Processos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('movement_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Movimentação')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='processes.processdata')),
            ],
            options={
                'verbose_name': 'Movimentação do Processo',
                'verbose_name_plural': 'Movimentações do Processo',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProcessNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('movement', 'Nova Movimentação'), ('status_change', 'Mudança de Status'), ('deadline', 'Prazo Próximo'), ('general', 'Geral')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='processes.processdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação de Processo',
                'verbose_name_plural': 'Notificações de Processos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nome')),
                ('party_type', models.CharField(choices=[('autor', 'Autor'), ('reu', 'Réu'), ('terceiro', 'Terceiro'), ('testemunha', 'Testemunha'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo da Parte')),
                ('document', models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento')),
                ('lawyer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Advogado')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='processes.processdata')),
            ],
            options={
                'verbose_name': 'Parte do Processo',
                'verbose_name_plural': 'Partes do Processo',
            },
        ),
        migrations.CreateModel(
            name='ProcessSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_number', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Número do processo deve estar no formato: NNNNNNN-DD.AAAA.J.TR.OOOO', regex='^\\d{7}-\\d{2}\\.\\d{4}\\.\\d{1}\\.\\d{2}\\.\\d{4}$')])),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Busca de Processo',
                'verbose_name_plural': 'Buscas de Processos',
                'ordering': ['-search_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProcessFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='processes.processdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_processes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processo Favorito',
                'verbose_name_plural': 'Processos Favoritos',
                'unique_together': {('user', 'process')},
            },
        ),
    ]
