# Generated by Django 5.2.5 on 2025-09-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processdata',
            name='process_number',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
