# Generated by Django 5.2.5 on 2025-09-24 03:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_alter_processdata_process_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processsearch',
            name='process_number',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Número do processo deve estar no formato: NNNNNNN-DD.AAAA.J.TR.OOOO ou apenas 20 dígitos', regex='^(\\d{7}-\\d{2}\\.\\d{4}\\.\\d{1}\\.\\d{2}\\.\\d{4}|\\d{20})$')]),
        ),
    ]
